# Generated by Django 5.0.6 on 2024-06-17 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('vendorid', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vendor_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorLogin',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendordetails.vendordetails')),
            ],
            options={
                'db_table': 'vendor_login',
                'managed': True,
            },
        ),
    ]
