# Generated by Django 5.0.6 on 2024-06-17 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendordetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDetail',
            fields=[
                ('inventory_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('inventory_title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendordetails.vendordetails')),
            ],
            options={
                'db_table': 'inventory_details',
                'managed': True,
            },
        ),
    ]
