# Generated by Django 5.0.6 on 2024-06-14 09:40

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usertable_created_at_alter_usertable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 9, 40, 44, 628326)),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='userid',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
    ]
