# Generated by Django 5.0.6 on 2024-06-14 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usertable_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 12, 23, 53, 499273)),
        ),
    ]
