# Generated by Django 5.0.6 on 2024-06-17 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usertable_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
