# Generated by Django 5.0.6 on 2024-06-17 12:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_usertable_created_at'),
        ('vendordetails', '0002_inventorydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('category_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'category_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('stock_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('stock_title', models.CharField(max_length=56)),
                ('stock_description', models.CharField(max_length=255)),
                ('stock_price', models.FloatField()),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.categorydetails')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendordetails.inventorydetail')),
            ],
            options={
                'db_table': 'stock_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurchasedHistory',
            fields=[
                ('purchased_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('status', models.CharField(default='Order Placed', max_length=30)),
                ('payment_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('purchased_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usertable')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockdetails')),
            ],
            options={
                'db_table': 'purchased_history',
                'managed': True,
            },
        ),
    ]
