# Generated by Django 5.0.6 on 2024-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetails',
            name='category_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
