# Generated by Django 5.0.6 on 2024-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_categorydetails_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
    ]
